# Generated by Django 3.1.7 on 2021-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_auto_20210307_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.IntegerField(unique=True),
        ),
    ]
